### ISSUE TITLE
curb segfault if on_progress returns false to abort transfer

### ISSUE THREAD

**Issue by pkoshevoy** [taf2/curb#192]
Below are a simple download helper class (using Curb) and the rspec test (a result of my first 2 days working with Ruby).  To reproduce the interpreter crash simply run rspec spec/downloader_spec.rb

The stack trace is as follows (produced with gdb on openSuSE 13.1 using system ruby2.0 and libcurl with debug symbols installed, and curb 0.8.5 gem)

```
#0  0x00007ffff7a9c3df in st_lookup (table=0x7ffff79f0af0 <proc_free>, key=key@entry=4184, value=value@entry=0x7fffffffcae8) at st.c:414
#1  0x00007ffff7ae395f in lookup_method_table (id=4184, klass=15753680) at vm_method.c:182
#2  search_method (defined_class_ptr=<synthetic pointer>, id=4184, klass=15753680) at vm_method.c:506
#3  rb_method_entry_get_without_cache (klass=15753680, id=4184, defined_class_ptr=0x7fffffffcb48) at vm_method.c:525
#4  0x00007ffff7ae3a3f in rb_method_entry (klass=klass@entry=15753680, id=id@entry=4184, defined_class_ptr=defined_class_ptr@entry=0x7fffffffcb48) at vm_method.c:565
#5  0x00007ffff7aed627 in rb_search_method_entry (defined_class_ptr=0x7fffffffcb48, mid=4184, recv=15753760) at vm_eval.c:523
#6  rb_call0 (recv=15753760, mid=4184, argc=4, argv=0x7fffffffcc00, scope=CALL_FCALL, self=6710440) at vm_eval.c:315
#7  0x00007ffff7aedca1 in rb_call (scope=CALL_FCALL, argv=<optimized out>, argc=4, mid=140737488342160, recv=<optimized out>) at vm_eval.c:585
#8  rb_funcall (recv=<optimized out>, mid=mid@entry=4184, n=n@entry=4) at vm_eval.c:794
#9  0x00007ffff5a00e9e in call_progress_handler (ary=ary@entry=15986840) at curb_easy.c:143
#10 0x00007ffff79ec7b6 in rb_rescue2 (b_proc=b_proc@entry=0x7ffff5a00e20 <call_progress_handler>, data1=data1@entry=15986840, r_proc=r_proc@entry=0x7ffff59ff7e0 <callback_exception>, data2=data2@entry=8)
    at eval.c:714
#11 0x00007ffff79ec8c4 in rb_rescue (b_proc=b_proc@entry=0x7ffff5a00e20 <call_progress_handler>, data1=data1@entry=15986840, r_proc=r_proc@entry=0x7ffff59ff7e0 <callback_exception>, data2=data2@entry=8)
    at eval.c:766
#12 0x00007ffff5a0369e in proc_progress_handler (proc=15753760, dltotal=<optimized out>, dlnow=<optimized out>, ultotal=<optimized out>, ulnow=<optimized out>) at curb_easy.c:169
#13 0x00007ffff579a399 in Curl_pgrsUpdate (conn=conn@entry=0x14fc900) at progress.c:375
#14 0x00007ffff579a804 in Curl_pgrsDone (conn=conn@entry=0x14fc900) at progress.c:139
#15 0x00007ffff57b0e58 in Curl_done (connp=connp@entry=0x15b8020, status=<optimized out>, premature=premature@entry=true) at url.c:5682
#16 0x00007ffff57c3c04 in curl_multi_remove_handle (multi_handle=0x17ca9c0, curl_handle=curl_handle@entry=0x15b8010) at multi.c:570
#17 0x00007ffff57a974a in Curl_close (data=data@entry=0x15b8010) at url.c:394
#18 0x00007ffff57bc55a in curl_easy_cleanup (curl=0x15b8010) at easy.c:590
#19 0x00007ffff59ff864 in ruby_curl_easy_free (rbce=rbce@entry=0x15c9b90) at curb_easy.c:212
#20 0x00007ffff59ff879 in curl_easy_free (rbce=0x15c9b90) at curb_easy.c:217 
#21 0x00007ffff79fcc41 in run_final (objspace=0x6040c0, objspace=0x6040c0, obj=15754720) at gc.c:1415
#22 finalize_list (objspace=objspace@entry=0x6040c0, p=0xf065e0, p@entry=0x17df3d8) at gc.c:1429
#23 0x00007ffff7a014fc in rb_objspace_call_finalizer (objspace=0x6040c0) at gc.c:1552
#24 rb_gc_call_finalizer_at_exit () at gc.c:1484
#25 0x00007ffff79edcfa in ruby_finalize_1 () at eval.c:127
#26 ruby_cleanup (ex=0) at eval.c:193
#27 0x00007ffff79edeb5 in ruby_run_node (n=0x991420) at eval.c:307
#28 0x000000000040091b in main (argc=3, argv=0x7fffffffd758) at main.c:36
```

Contents of lib/downloader.rb download helper are as follows:

``` ruby
require 'curb'

module Sorensond
  class Downloader

    attr_accessor :on_progress, :on_abort

    def initialize(url, &block)
      @url = url
      yield(self) if block_given?
    end

    def download(&block)
      return unless block_given?

      begin
        response = Curl.get(@url) do |curl|
          curl.on_progress do |download_total, downloaded_now, upload_total, uploaded_now|

            # Check whether we need to abort the download:
            if not @on_abort.nil?
              return false if @on_abort.call
            end

            # report progress if requested:
            if not @on_progress.nil?
              @on_progress.call(downloaded_now, download_total)
            end

            # don't abort, continue downloading:
            true
          end

          curl.on_body do |chunk|
            block.call(chunk)

            # curb (curl) needs to know how many bytes were consumed:
            chunk.size
          end
        end

        # FIXME: this is too specific
        return false unless response.response_code == 200
      rescue
        return false
      end

      true
    end
  end
end
```

Contents of spec/downloader_spec.rb are as follows:

``` ruby
require_relative '../lib/downloader'

module Sorensond

  class Downloader
    attr_reader :uri
  end

  describe Downloader do

    let(:url_http)  { 'http://google.com' }

    context "Protocol HTTP" do

      context "Is successful" do

        let(:downloader) { Downloader.new(url_http) }

        subject { downloader }

        it "should send at least one chunk" do
          chunk_counter = 0
          downloader.on_abort = lambda { return true if chunk_counter > 0 }

          downloader.download do |chunk|
            chunk_counter  += 1
          end

          chunk_counter.should be > 0
        end
      end
    end
  end
end
```

**Comment by taf2** [comment]
8 years later and this return issue is resolved :)

**Comment by taf2** [comment]
```
 ruby --version
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin22]
~/work/curb (master)> ruby tests/bug_crash_on_progress.rb
Loaded suite tests/bug_crash_on_progress
Started
we're in the progress callback
..
Finished in 0.005361 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------
373.06 tests/s, 186.53 assertions/s
```
