### ISSUE TITLE
curb_core.bundle requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

### ISSUE THREAD

**Issue by petrbela** [taf2/curb#338]
I might be missing something but the latest `curl` version is 7.54.0

```sh
$ curl -V
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

Why does curb require version 9.0.0?

```sh
/Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curl.rb:1:in `require': dlopen(/Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curb_core.bundle, 9): Library not loaded: @rpath/libcurl.4.dylib (LoadError)
  Referenced from: /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curb_core.bundle
  Reason: Incompatible library version: curb_core.bundle requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0 - /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curb_core.bundle
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curl.rb:1:in `<top (required)>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curb.rb:1:in `require'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/curb-0.9.4/lib/curb.rb:1:in `<top (required)>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/badge-0.8.7/lib/badge/runner.rb:4:in `require'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/badge-0.8.7/lib/badge/runner.rb:4:in `<top (required)>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/badge-0.8.7/lib/badge.rb:2:in `require'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/badge-0.8.7/lib/badge.rb:2:in `<top (required)>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-plugin-badge-1.0.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:5:in `require'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-plugin-badge-1.0.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:5:in `available_options'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-plugin-badge-1.0.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:22:in `available_options'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-plugin-badge-1.0.0/lib/fastlane/plugin/badge/actions/add_badge_action.rb:47:in `available_options'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:241:in `block (2 levels) in execute_action'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:230:in `chdir'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:230:in `execute_action'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:83:in `block (2 levels) in parsing_binding'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/gems/fastlane-2.81.0/bin/fastlane:20:in `<top (required)>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/bin/fastlane:22:in `load'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/bin/fastlane:22:in `<main>'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/petrbela/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by christianroy** [comment]
@petrbela Maybe you figured it out, but just in case... Got the same issue, and after spending a lot of time trying to fix it, here is what did the job for me: https://stackoverflow.com/a/47115793/7599189

**Comment by taf2** [comment]
for reference:

```
gem pristine curb 
```
