### ISSUE TITLE
Getting error "The specified module could not be found..."  for  curb_core.so file even though it exist in that location

### ISSUE THREAD

**Issue by olgagod** [taf2/curb#352]
Hi
I have Ruby 2.4.4 installed on Win 10 .  It took me a while to install gem curb. Now, when I'm running  require 'curb' command in irb, I'm getting error "LoadError: 126: The specified module could not be found.   - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/curb-0.9.6/lib/curb_core.so" .  I checked the location and file curb_core.so does exist there. Why it does not see it? PLEASE HELP!

Here is the output from cmd:

C:\Windows\System32>gem install curb --platform=ruby -- --with-curl-dir="C:\curl-7.61.0-win64-mingw" --with-curl-lib="C:\curl-7.61.0-win64-mingw\bin" --with-curl-include="C:\curl-7.61.0-win64-mingw\include"
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--with-curl-dir=C:\curl-7.61.0-win64-mingw --with-curl-lib=C:\curl-7.61.0-win64-mingw\bin --with-curl-include=C:\curl-7.61.0-win64-mingw\include'
This could take a while...
Successfully installed curb-0.9.6
Parsing documentation for curb-0.9.6
Done installing documentation for curb after 1 seconds
1 gem installed

C:\Windows\System32>irb
irb(main):001:0> require 'curb'
LoadError: 126: The specified module could not be found.   - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/curb-0.9.6/lib/curb_core.so
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/curb-0.9.6/lib/curl.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/curb-0.9.6/lib/curb.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby24-x64/bin/irb.cmd:19:in `<main>'
irb(main):002:0>

**Comment by olgagod** [comment]
I solved it by uninstalling Ruby 2.4.4 64 bit and installing Ruby 2.4.4 32 bit.
Then I used this instructions to install curb
http://blog.cloud-mes.com/2014/08/19/how-to-install-gem-curb-in-windows/
Now I can use curb
irb(main):002:0> require 'curb'
=> true
