### ISSUE TITLE
Gems '@rpath/libssl.1.1.dylib' not found

### ISSUE THREAD

**Issue by cchinnaraj** [taf2/curb#388]
[02:46:44]: ▸ /Users/<>/.gem/gems/curb-0.9.10/lib/curl.rb:2:in `require': dlopen(/Users/<>/.gem/gems/curb-0.9.10/lib/curb_core.bundle, 0x0009): dependent dylib '@rpath/libssl.1.1.dylib' not found for '/Users/<>/.gem/gems/curb-0.9.10/lib/curb_core.bundle' - /Users/<>/.gem/gems/curb-0.9.10/lib/curb_core.bundle (LoadError)
[02:46:44]: ▸ from /Users/<>/.gem/gems/curb-0.9.10/lib/curl.rb:2:in `<top (required)>'
[02:46:44]: ▸ from /Users/<>/.gem/gems/curb-0.9.10/lib/curb.rb:2:in `require'
[02:46:44]: ▸ from /Users/<>/.gem/gems/curb-0.9.10/lib/curb.rb:2:in `<top (required)>'

I am install curb using GemFile.

**Comment by cchinnaraj** [comment]
Can anyone help me to resolve this issue please. ?

**Comment by taf2** [comment]
I am assuming you're on OSX?   

```
brew install curl
```

make sure you're on ruby 2.6 or 2.7?

gem install curb

**Comment by cchinnaraj** [comment]
Closing this bug, This looks resolved in latest release.
