### ISSUE TITLE
[BUG] Curl::PostField.content - Segmentation fault

### ISSUE THREAD

**Issue by airled** [taf2/curb#392]
Tech description:

OS: `Ubuntu 16.04`
Ruby: `2.6.3`
Curb: `0.9.10`

Reproduce:
```
require 'curb'
c = Curl::Easy.new('http://ANY_URL')
c.multipart_form_post = true
c.http_post(
  Curl::PostField.content('param', 123),
  Curl::PostField.file('document', 'ANY_FILE')
)
```

Exception stack (not all) with irb:
```
irb(main):019:0>       c = Curl::Easy.new('http://ya.ru')
=> #<Curl::Easy http://ya.ru>
irb(main):020:0>       c.multipart_form_post = true
=> true
irb(main):021:0>       c.http_post(
irb(main):022:1*         Curl::PostField.content('param', 123),
irb(main):023:1*         Curl::PostField.file('document', '/home/air/123.txt')
irb(main):024:1>       )
(irb):21: [BUG] Segmentation fault at 0x00000000000000f7
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0022 p:---- s:0108 e:000107 CFUNC  :http_post
c:0021 p:0038 s:0102 e:000101 EVAL   (irb):21 [FINISH]
c:0020 p:---- s:0099 e:000098 CFUNC  :eval
c:0019 p:0021 s:0091 e:000090 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/workspace.rb:85
c:0018 p:0056 s:0083 e:000081 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/context.rb:385
c:0017 p:0020 s:0074 e:000073 BLOCK  /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:493
c:0016 p:0025 s:0071 e:000070 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:647
c:0015 p:0008 s:0065 e:000064 BLOCK  /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:490
c:0014 p:0100 s:0060 e:000059 BLOCK  /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:246 [FINISH]
c:0013 p:---- s:0056 e:000055 CFUNC  :loop
c:0012 p:0006 s:0052 e:000051 BLOCK  /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:232 [FINISH]
c:0011 p:---- s:0049 e:000048 CFUNC  :catch
c:0010 p:0012 s:0044 e:000043 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:231
c:0009 p:0034 s:0040 E:0014f8 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:489
c:0008 p:0005 s:0035 e:000034 BLOCK  /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:428 [FINISH]
c:0007 p:---- s:0032 e:000031 CFUNC  :catch
c:0006 p:0064 s:0027 E:001ca8 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:427
c:0005 p:0102 s:0022 e:000021 METHOD /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:383
c:0004 p:0019 s:0016 e:000015 TOP    /home/air/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0109 s:0008 E:0014e0 EVAL   /home/air/.asdf/installs/ruby/2.6.3/bin/irb:23 [FINISH]
c:0001 p:0000 s:0003 E:001630 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/air/.asdf/installs/ruby/2.6.3/bin/irb:23:in `<main>'
/home/air/.asdf/installs/ruby/2.6.3/bin/irb:23:in `load'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:383:in `start'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:427:in `run'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:427:in `catch'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:428:in `block in run'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:490:in `block in eval_input'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb.rb:493:in `block (2 levels) in eval_input'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/home/air/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
(irb):21:in `irb_binding'
(irb):21:in `http_post'
```

Reason: **Integer value** in Curl::PostField.content
Fix: Change `Curl::PostField.content('param', 123)` to `Curl::PostField.content('param', '123')`

I think, Curb should cast value to string automatically or at least do not crash runtime with C stack.

**Comment by luke-hill** [comment]
This is something I've seen before.

According to the regular POST/GET/REST calls, all items are sent as strings. If you send `"123"` does it crash?

And yes, perhaps we should forcibly cast everything to strings as we send them. Good point

**Comment by airled** [comment]
@luke-hill No, it does not crash if you pass value as a string

**Comment by taf2** [comment]
@airled in recent versions of curb i don't get a segfault instead i get:
```
TypeError (no implicit conversion of Integer into String)
```
