### ISSUE TITLE
LoadError - undefined symbol: MD5_Init

### ISSUE THREAD

**Issue by qgtim** [taf2/curb#396]
When using a very basic setup and IRB, I am getting a load error.

```
irb(main):001:0> require 'curb'
Traceback (most recent call last):
        9: from /app/bin/irb:30:in `<main>'
        8: from /app/bin/irb:30:in `load'
        7: from /app/vendor/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        6: from (irb):1
        5: from (irb):1:in `require'
        4: from /app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curb.rb:2:in `<top (required)>'
        3: from /app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curb.rb:2:in `require'
        2: from /app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curl.rb:2:in `<top (required)>'
        1: from /app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curl.rb:2:in `require'
LoadError (/app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curb_core.so: undefined symbol: MD5_Init - /app/vendor/bundle/ruby/2.6.0/gems/curb-0.9.10/lib/curb_core.so)
```

Gemfile:
```
source 'http://rubygems.org'
ruby '2.6.5'

gem 'curb'
```

I am using [heroku-18](https://devcenter.heroku.com/articles/heroku-18-stack) with the [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt) multipack.

Aptfile:
```
libcurl4-openssl-dev
```

The gem installs fine.  Just cannot use it without the load error.  Is there some other package I need to install to get MD5 to initialize properly?

**Comment by luke-hill** [comment]
you need more than just that one file. Check the readme for a guide to what needs installing.

Also before doing anything, check gem install curb works
