### ISSUE TITLE
Error Installing on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by glhcaml-fsl** [taf2/curb#450]
OS: Ubuntu 20.04.6 LTS

libcurl4:
  Installed: 7.68.0-1ubuntu2.22

libcurl3-gnutls:
  Installed: 7.68.0-1ubuntu2.22

libcurl4-openssl-dev:
  Installed: 7.68.0-1ubuntu2.22
 ``` 
> gem install curb

Building native extensions. This could take a while...
ERROR:  Error installing curb:
	ERROR: Failed to build gem native extension.

    current directory: /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/curb-1.0.5/ext
/home/glhcaml/.asdf/installs/ruby/3.2.2/bin/ruby extconf.rb
checking for curl-config... yes
checking for curlopt_tcp_keepalive... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/glhcaml/.asdf/installs/ruby/3.2.2/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
/home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:616:in `block in try_compile'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:565:in `with_werror'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:616:in `try_compile'
	from extconf.rb:54:in `block in have_constant'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:989:in `block in checking_for'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:354:in `block (2 levels) in postpone'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:354:in `block in postpone'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:350:in `postpone'
	from /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/mkmf.rb:988:in `checking_for'
	from extconf.rb:46:in `have_constant'
	from extconf.rb:64:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/curb-1.0.5/mkmf.log

extconf failed, exit code 1
```

**Comment by taf2** [comment]
Would be helpful to see: ```To see why this extension failed to compile, please check the mkmf.log which can be found here:

 /home/glhcaml/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/curb-1.0.5/mkmf.log
```

**Comment by taf2** [comment]
make sure you have a compiler installed etc...
