### ISSUE TITLE
Rake compile task stuck on ruby 2.3.8

### ISSUE THREAD

**Issue by uvlad7** [taf2/curb#456]
I understand that 2.3.8 is really old and rake is not that important - gem install for packaged gem works fine - just want to let you know.

When I run `rake compile`, it reaches `make step` and just sleeps

```bash
curb (master)$ ps u --ppid 2643474
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
vladimir 2643477  0.0  0.0  11936  2944 pts/5    S+   22:52   0:00 gcc -I. -I/home/vladimir/.local/share/rtx/installs/ruby/2.3.8/include/ruby-2.3.0/x86_64-linux -I/home/vladimir/.local/share/rtx/installs/ruby/2.3.8/include/ruby-2.3.0/ruby/backward -I/home/vladimir/.local/share/rtx/i
curb (master)$ ps u -p 2643474
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
vladimir 2643474  0.0  0.0  11420  2816 pts/5    S+   22:52   0:00 make

```

```bash
curb (master)$ rake compile
> make
compiling curb_easy.c

^Crake aborted!
Interrupt: 
tasks/utils.rb:34:in `gets'
tasks/utils.rb:34:in `block in execute!'
tasks/utils.rb:30:in `execute!'
tasks/utils.rb:20:in `block in run_command'
tasks/utils.rb:20:in `chdir'
tasks/utils.rb:20:in `run_command'
tasks/rake_helpers.rb:45:in `shell'
/home/vladimir/profit/curb/Rakefile:60:in `make'
/home/vladimir/profit/curb/Rakefile:67:in `block in <top (required)>'
Tasks: TOP => compile => ext/curb_core.so
```

but `make` itself works

```bash
curb/ext (master)$ make 2>/dev/null 
compiling curb.c
compiling curb_easy.c
compiling curb_errors.c
compiling curb_multi.c
compiling curb_postfield.c
compiling curb_upload.c
linking shared-object curb_core.so
```

**Comment by taf2** [comment]
Check the latest release it looks like the wrong shell was being used.
